name: Docker Build

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@master
        with:
          image: mrsmithers/terraform-gh-actions
          registry: docker.io
          tag: 0.12.12
          username: mrsmithers
          password: ${{ secrets.DOCKER_PASSWORD }}
